# Generated by Django 4.0 on 2026-06-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopost',
            old_name='posted_add',
            new_name='posted_at',
        ),
    ]
